
variables:
  ANSIBLE_GALAXY_PACKAGE_NAME: phpipam_scanagent
  GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/docker-bind.git"
  GIT_SUBMODULE_PATHS: gitlab-ci


include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - .gitlab-ci_common.yaml
      - template/ansible-collection.gitlab-ci.yaml
      # ToDo: update gitlabCI jobs for collections workflow
      - git_push_mirror/.gitlab-ci.yml
