- name: Agent Webhook
  hosts: all

  sources:
    - name: Webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: "{{ nofusscomputing_phpipam_scan_server.http_port | default(5000) | int }}"
        token: "{{ nofusscomputing_phpipam_scan_server.auth_token | default('no-token-set') }}"

  rules:

    - name: Process inbound Subnet Scans
      condition: true    # Always run action
      actions:


        - print_event:
            pretty: true


        - run_playbook:
            name: nofusscomputing.phpipam_scan_agent.server
            extra_vars:
              inbound_data: "{{ event.payload }}"
