- name: Fetch API Data
  hosts: localhost
  become: false
  gather_facts: false

  tasks:

    - name: Create API Cache Directory
      ansible.builtin.file:
        path: "{{ nfc_c_path_cache }}"
        state: directory

    - name: Agent ID
      ansible.builtin.include_tasks:
        file: tasks/agent_id.yaml


    - name: Subnets
      ansible.builtin.include_tasks:
        file: tasks/subnets.yaml

  vars: # ToDo: remove the below t4est vars
    api_subnets: subnets
    api_scanagents: tools/scanagents
    nfc_c_path_cache: "{{ playbook_dir }}/../cache"
    nfc_c_cache_expire_time: 1800
    nfc_c_epoch_time_offset: "{{ -((3600 * 9) + 1800 | int) | int }}"
